"use client";
import { FC } from "react";

const Head: FC = () => {
  return (
    <>
      <title>Panaverse DAO</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/Logo.png" />
    </>
  )
};

export default Head;