"use client"
import { FC } from 'react';
import styles from './page.module.css';

const Home: FC = () => {
    return (
        <main className={styles.main}>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
            <h1>
                Hello
            </h1>
        </main>
    )
};

export default Home;